name = "palabres_wisp"
version = "0.4.0"
target = "erlang"

description = "Wisp integration for palabres, an opinionated logger for Gleam"
licences = ["MIT"]

[[links]]
title = "Sponsor"
href = "https://github.com/sponsors/ghivert"

[repository]
type = "github"
user = "ghivert"
repo = "palabres"
path = "palabres_wisp"

[dependencies]
gleam_http = ">= 3.5.0 and < 5.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
palabres = ">= 0.4.0 and < 1.0.0"
wisp = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
startest = ">= 0.6.0 and < 1.0.0"
