name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-palabres:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.8.1"
          rebar3-version: "3.24.0"
      - run: gleam deps download
        working-directory: palabres
      - run: gleam test
        working-directory: palabres
      - run: gleam format --check src test
        working-directory: palabres

  test-palabres_wisp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.8.1"
          rebar3-version: "3.24.0"
      - run: gleam deps download
        working-directory: palabres_wisp
      - run: gleam test
        working-directory: palabres_wisp
      - run: gleam format --check src test
        working-directory: palabres_wisp
